<?php

namespace Tests\Feature\Http\Controllers;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\CoachController
 */
class CoachControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function delete_coach_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = \App\Models\User::factory()->create();

        $response = $this->get(route('delete.coach', ['id' => $id]));

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function edit_coach_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = \App\Models\User::factory()->create();
        $teams = \App\Models\Teams::factory()->times(3)->create();
        $squads = \App\Models\Squad::factory()->times(3)->create();

        $response = $this->get(route('edit.coach', ['id' => $id]));

        $response->assertOk();
        $response->assertViewIs('admin.coaches.coach_registration.edit_coach');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function new_coach_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $teams = \App\Models\Teams::factory()->times(3)->create();
        $squads = \App\Models\Squad::factory()->times(3)->create();

        $response = $this->get(route('new.coach'));

        $response->assertOk();
        $response->assertViewIs('admin.coaches.coach_registration.new_coach');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function save_coach_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->post(route('save.coach'), [
            // TODO: send request data
        ]);

        $response->assertRedirect(route('view.coach'));

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function update_coach_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = \App\Models\User::factory()->create();

        $response = $this->post(route('update.coach', ['id' => $id]), [
            // TODO: send request data
        ]);

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function view_coaches_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $users = \App\Models\User::factory()->times(3)->create();

        $response = $this->get(route('view.coach'));

        $response->assertOk();
        $response->assertViewIs('admin.coaches.coach_registration.view_coaches');

        // TODO: perform additional assertions
    }

    // test cases...
}
