<?php

namespace Tests\Feature\Http\Controllers;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\ContractController
 */
class ContractControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function delete_contract_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $contracts = \App\Models\Contracts::factory()->create();

        $response = $this->get(route('delete.contract', ['id' => $id]));

        $response->assertRedirect(route('view.contract'));

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function edit_contract_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $contracts = \App\Models\Contracts::factory()->create();

        $response = $this->get(route('edit.contract', ['id' => $id]));

        $response->assertOk();
        $response->assertViewIs('admin.contracts.edit_contract');
        $response->assertViewHas('editData');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function new_contract_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('new.contract'));

        $response->assertOk();
        $response->assertViewIs('admin.contracts.add_contract');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function save_contract_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->post(route('save.contract'), [
            // TODO: send request data
        ]);

        $response->assertRedirect(route('view.contract'));

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function update_contract_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $contracts = \App\Models\Contracts::factory()->create();

        $response = $this->post(route('update.contract', ['id' => $id]), [
            // TODO: send request data
        ]);

        $response->assertRedirect(route('view.contract'));

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function view_contract_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $contracts = \App\Models\Contracts::factory()->times(3)->create();

        $response = $this->get(route('view.contract'));

        $response->assertOk();
        $response->assertViewIs('admin.contracts.view_contract');

        // TODO: perform additional assertions
    }

    // test cases...
}
