<?php

namespace Tests\Feature\Http\Controllers;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\HomeController
 */
class HomeControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function index_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $fixtures = \App\Models\Fixture::factory()->times(3)->create();

        $response = $this->get(route('home'));

        $response->assertOk();
        $response->assertViewIs('admin.dashboard');
        $response->assertViewHas('fixtures', $fixtures);
        $response->assertViewHas('num_players');
        $response->assertViewHas('num_coaches');
        $response->assertViewHas('num_alliances');

        // TODO: perform additional assertions
    }

    // test cases...
}
