<?php

namespace Tests\Feature\Http\Controllers;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\StatisticController
 */
class StatisticControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function edit_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $player = \App\Models\Player::factory()->create();

        $response = $this->get(route('edit.statistic', [$player]));

        $response->assertOk();
        $response->assertViewIs('admin.players.statistics');
        $response->assertViewHas('player', $player);

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function generate_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('generate.statistic'));

        $response->assertOk();
        $response->assertViewIs('admin.generate_stats');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function update_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $statistic = \App\Models\Statistic::factory()->create();

        $response = $this->post(route('update.statistic', [$statistic]), [
            // TODO: send request data
        ]);

        $response->assertOk();

        // TODO: perform additional assertions
    }

    // test cases...
}
